export const Courses = [
    {
        id: '1',
        title: "Web Development",
        image:require('../../assets/images/web1.jpg'),
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna.",
        Course1: "HTML",
        Course2: "CSS",
        Course3: "JavaScript",
        price: 5000,
    },
    {
        id: '2',
        title: "Graphic Designing",
        image:require('../../assets/images/graphic.jpg'),
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna.",
        Course1: "Pi",
        Course2: "ADB",
        Course3: "Adobe Photoshoot",
        price: 2000,
    },
    {
        id: '3',
        title: "App Development",
        image:require('../../assets/images/app.jpg'),
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna.",
        Course1: "HTML",
        Course2: "CSS",
        Course3: "React Native",
        price: 4000,
    },
    {
        id: '4',
        title: "Matchine Learning",
        image:require('../../assets/images/web1.jpg'),
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna.",
        Course1: "HTML",
        Course2: "CSS",
        Course3: "JavaScript",
        price: 6000,
    },
    {
        id: '5',
        title: "Ethical Hacking",
        image:require('../../assets/images/hack.jpg'),
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna.",
        Course1: "HTML",
        Course2: "CSS",
        Course3: "JavaScript",
        price: 3000,
    },
    {
        id: '6',
        title: "Digital Marketing",
        image:require('../../assets/images/digital.jpg'),
        description: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Sed do eiusmod tempor incididunt ut labore et dolore magna.",
        Course1: "Content Writing",
        Course1: "SEO",
        Course1: "Social Media Marketing",
        price: 3500,
    }
]